image: mono:latest

before_script:
    - nuget restore -NonInteractive

build:
    script:
    - xbuild "WindowsBashHere.sln"
    - mkdir Release/
    - cp -R WindowsBashHere/bin/Debug/* Release/
    artifacts:
        name: "WindowsBashHere_${CI_BUILD_REF_NAME}"
        paths:
        - Release/